import pytest

from hme_bitwarden.aliases import AliasService, RateLimited, SlidingWindowLimiter, clean, derive_label
from hme_bitwarden.icloud import AccountState

from .conftest import FakeBackend


@pytest.mark.parametrize(
    ("hostname", "description", "expected"),
    [
        ("shop.example.com", "", "shop.example.com"),
        ("", "Website: Example.ORG. Generated by Bitwarden.", "example.org"),
        ("", "Webseite: beispiel.de. Generiert von Bitwarden.", "beispiel.de"),
        ("", "Generated by Bitwarden.", "Bitwarden"),
        ("", "", "Bitwarden"),
        ("not a host", "", "Bitwarden"),
    ],
)
def test_derive_label(hostname, description, expected):
    assert derive_label(hostname, description) == expected


def test_clean_removes_control_characters_and_truncates():
    assert clean("a\nb\x00c   ", 10) == "a b c"
    assert clean("x" * 300, 200) == "x" * 200


def test_sliding_window_limiter():
    now = [0.0]
    limiter = SlidingWindowLimiter(2, 60, clock=lambda: now[0])
    assert limiter.try_acquire()
    assert limiter.try_acquire()
    assert not limiter.try_acquire()
    now[0] = 61
    assert limiter.try_acquire()


def test_service_keeps_recent_history_newest_first():
    backend = FakeBackend()
    backend.state = AccountState.READY
    service = AliasService(backend, max_per_hour=10)
    service.create(hostname="a.example")
    service.create(hostname="b.example")
    assert [a.label for a in service.recent] == ["b.example", "a.example"]


def test_service_rate_limit():
    backend = FakeBackend()
    backend.state = AccountState.READY
    service = AliasService(backend, max_per_hour=1)
    service.create()
    with pytest.raises(RateLimited):
        service.create()
