from hme_bitwarden.icloud import AccountState, AppleApiError

from .conftest import API_TOKEN

SIMPLELOGIN = "/api/alias/random/new"
ADDY = "/api/v1/aliases"


def simplelogin_headers(token: str = API_TOKEN) -> dict[str, str]:
    return {"Authentication": token, "Content-Type": "application/json"}


def test_simplelogin_creates_alias_labeled_with_hostname(client, backend):
    backend.state = AccountState.READY
    response = client.post(
        f"{SIMPLELOGIN}?hostname=shop.example.com",
        headers=simplelogin_headers(),
        json={"note": "Website: shop.example.com. Generated by Bitwarden."},
    )
    assert response.status_code == 201
    assert response.json() == {"alias": "alias1@icloud.com"}
    assert backend.created == [("shop.example.com", "Website: shop.example.com. Generated by Bitwarden.")]


def test_addy_io_creates_alias_labeled_from_description(client, backend):
    backend.state = AccountState.READY
    response = client.post(
        ADDY,
        headers={"Authorization": f"Bearer {API_TOKEN}"},
        json={"domain": "icloud.com", "description": "Website: news.example.org. Generated by Bitwarden."},
    )
    assert response.status_code == 201
    assert response.json() == {"data": {"email": "alias1@icloud.com"}}
    assert backend.created[0][0] == "news.example.org"


def test_missing_body_uses_defaults(client, backend):
    backend.state = AccountState.READY
    response = client.post(SIMPLELOGIN, headers={"Authentication": API_TOKEN})
    assert response.status_code == 201
    assert backend.created == [("Bitwarden", "Created by Bitwarden")]


def test_invalid_token_is_rejected(client, backend):
    backend.state = AccountState.READY
    response = client.post(SIMPLELOGIN, headers=simplelogin_headers("wrong"))
    assert response.status_code == 401
    assert response.json() == {"error": "Invalid API key"}
    assert backend.created == []


def test_missing_token_is_rejected(client):
    assert client.post(ADDY, json={}).status_code == 401


def test_client_is_locked_out_after_repeated_failures(client, backend):
    backend.state = AccountState.READY
    for _ in range(10):
        assert client.post(SIMPLELOGIN, headers=simplelogin_headers("wrong")).status_code == 401
    # Even the correct token is refused while locked out.
    response = client.post(SIMPLELOGIN, headers=simplelogin_headers())
    assert response.status_code == 429


def test_signed_out_returns_actionable_error(client):
    response = client.post(SIMPLELOGIN, headers=simplelogin_headers())
    assert response.status_code == 503
    assert response.json()["error"] == "iCloud: Not signed in yet. Sign in again at https://hme.example.com"


def test_apple_error_is_passed_through(client, backend):
    backend.state = AccountState.READY
    backend.error = AppleApiError("You have reached the limit of addresses you can create at this time")
    response = client.post(SIMPLELOGIN, headers=simplelogin_headers())
    assert response.status_code == 502
    assert "limit of addresses" in response.json()["error"]


def test_hourly_limit(client, backend):
    backend.state = AccountState.READY
    for _ in range(5):
        assert client.post(SIMPLELOGIN, headers=simplelogin_headers()).status_code == 201
    response = client.post(SIMPLELOGIN, headers=simplelogin_headers())
    assert response.status_code == 429
    assert "limit" in response.json()["error"]


def test_failed_attempts_do_not_use_up_the_hourly_limit(client, backend):
    for _ in range(6):
        assert client.post(SIMPLELOGIN, headers=simplelogin_headers()).status_code == 503
    backend.state = AccountState.READY
    assert client.post(SIMPLELOGIN, headers=simplelogin_headers()).status_code == 201


def test_cors_preflight_allowed_for_api(client):
    response = client.options(
        ADDY,
        headers={
            "Origin": "https://vault.bitwarden.com",
            "Access-Control-Request-Method": "POST",
            "Access-Control-Request-Headers": "authorization,content-type",
        },
    )
    assert response.status_code == 200
    assert response.headers["access-control-allow-origin"] == "*"


def test_no_cors_outside_api(client):
    response = client.get("/login", headers={"Origin": "https://evil.example"})
    assert "access-control-allow-origin" not in response.headers


def test_api_responses_are_not_cached(client):
    response = client.post(SIMPLELOGIN, headers=simplelogin_headers())
    assert response.headers["cache-control"] == "no-store"
    assert response.headers["x-content-type-options"] == "nosniff"


def test_healthz(client):
    assert client.get("/healthz").json() == {"status": "ok"}
